import { FlatCompat } from '@eslint/eslintrc';

const compat = new FlatCompat({ baseDirectory: import.meta.dirname });

/**
 * The two rules below are architectural, not stylistic. They are the mechanism that keeps a
 * modular monolith from decaying into a mud ball, and they are why the tenancy guarantee holds.
 */
const config = [
  {
    ignores: [
      '.next/**',
      'node_modules/**',
      'coverage/**',
      'test-results/**',
      'playwright-report/**',
      // Generated by Next on every build; not ours to lint.
      'next-env.d.ts',
    ],
  },
  ...compat.extends('next/core-web-vitals', 'next/typescript'),

  {
    // Rule 1 — tenancy. Nothing may reach the Prisma client except the db platform module,
    // because that module is where organization scoping is injected. An import that bypasses
    // it is an unscoped query waiting to happen.
    files: ['src/**/*.{ts,tsx}', 'tests/**/*.ts'],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          paths: [
            {
              name: '@prisma/client',
              message:
                'Import from @/platform/db instead. Direct Prisma access bypasses organization scoping.',
            },
          ],
        },
      ],
    },
  },
  {
    // The db platform module is the one place allowed to hold the client.
    files: ['src/platform/db/**/*.ts', 'prisma/**/*.ts', 'tests/support/**/*.ts'],
    rules: { 'no-restricted-imports': 'off' },
  },

  {
    // Rule 2 — dependency direction: app -> modules -> platform. Never upward, and never
    // sideways between modules except through a module's public index.
    files: ['src/platform/**/*.ts'],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          patterns: [
            {
              group: ['@/modules/*', '@/app/*'],
              message:
                'platform is the lowest layer: it must not depend on a module or on the app.',
            },
          ],
        },
      ],
    },
  },
  {
    files: ['src/modules/**/*.ts'],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          patterns: [
            {
              group: ['@/app/*'],
              message: 'modules must not depend on the app layer.',
            },
            {
              group: ['@/modules/*/*'],
              message:
                "reach another module through its public index (@/modules/x), not its internals.",
            },
          ],
          paths: [
            {
              name: '@prisma/client',
              message:
                'Import from @/platform/db instead. Direct Prisma access bypasses organization scoping.',
            },
          ],
        },
      ],
    },
  },

  {
    rules: {
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
      '@typescript-eslint/no-explicit-any': 'error',
      eqeqeq: ['error', 'always'],
    },
  },

  /*
   * Application code logs through @/platform/observability, never through console.
   *
   * Not a style preference. The logger redacts credentials, tokens, payment evidence and raw
   * customer messages, and attaches the correlation id that makes a support call answerable. A
   * bare console.log does none of that, and the one that eventually prints a bank slip into a
   * log aggregator will have looked entirely reasonable when it was written.
   */
  {
    files: ['src/**/*.{ts,tsx}'],
    rules: {
      // The logger disables this on the one line that is allowed to write output, so the
      // exception is visible where it is taken rather than hidden in a config ignore list.
      'no-console': 'error',
    },
  },

  /* CLI scripts and the seed talk to an operator at a terminal. That is what console is for. */
  {
    files: ['scripts/**/*.ts', 'prisma/**/*.ts'],
    rules: {
      'no-console': 'off',
    },
  },

  /*
   * The CommonJS preload that lets CLI scripts import server-only modules.
   *
   * It has to be CommonJS and it has to use require(), because it is loaded with --require
   * before any ESM resolution happens. That is the whole mechanism.
   */
  {
    files: ['scripts/**/*.cjs'],
    rules: {
      '@typescript-eslint/no-require-imports': 'off',
      'no-undef': 'off',
    },
  },
];

export default config;
